# Use $POSTGRES_USER/$POSTGRES_PASSWORD user/password credentials
version: '3.1'

services:
    db:
        image: postgres:latest
        restart: always
        ports:
        - 5432:5432
        environment:
            POSTGRES_USER: $POSTGRES_USER
            POSTGRES_PASSWORD: $POSTGRES_PASSWORD
            POSTGRES_DB: $POSTGRES_DB


    adminer:
        image: adminer
        restart: always
        ports:
        - 8080:8080