# Use $POSTGRES_USER/$POSTGRES_PASSWORD user/password credentials
version: '3.1'

services:
    api:
        build: .
        image: maizovac-api
        environment: 
            PORT: $PORT
            DEFAULT_USERNAME: $DEFAULT_USERNAME
            DB_CONNECTION_STRING: $DB_CONNECTION_STRING
            AUTHORIZATION_DOMAIN: $AUTHORIZATION_DOMAIN
            AUTHORIZATION_AUDIENCE: $AUTHORIZATION_AUDIENCE
        ports:
            - 3000:3000

        stdin_open: true
        tty: true
        networks:
            - db
    db:
        image: postgres:latest
        restart: always
        ports:
        - 5432:5432
        environment:
            POSTGRES_USER: $DATABASE_USER
            POSTGRES_PASSWORD: $DATABASE_PASSWORD
            POSTGRES_DB: $DATABASE_NAME
        networks:
            - db

    adminer:
        image: adminer
        restart: always
        ports:
        - 8080:8080
        networks:
            - db

networks:
    db: