# Use $POSTGRES_USER/$POSTGRES_PASSWORD user/password credentials
version: '3.1'

services:
    api:
        build: .
        image: maizovac-api
        environment: 
            PORT: $PORT_PROD
            DEFAULT_USERNAME: $DEFAULT_USERNAME
            DB_CONNECTION_STRING: $DB_CONNECTION_STRING_PROD
        ports:
            - 3000:3000

        stdin_open: true
        tty: true
        networks:
            - db
    db:
        image: postgres:latest
        restart: always
        ports:
        - 5432:5432
        environment:
            POSTGRES_USER: $DATABASE_USER_PROD
            POSTGRES_PASSWORD: $DATABASE_PASSWORD_PROD
            POSTGRES_DB: $DATABASE_NAME_PROD
        networks:
            - db

    adminer:
        image: adminer
        restart: always
        ports:
        - 8080:8080
        networks:
            - db

networks:
    db: