/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface APIRecord {
    $schema?: 'api:record';
    uuid?: string;
    service: {
        [k: string]: unknown;
    };
    user: {
        [k: string]: unknown;
    };
    cost?: number;
    balance?: number;
    response?: string;
    date?: string;
}
