#%RAML 1.0
title: "Maizovac API"
version: v1
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost:3000
mediaType: application/json

types:
    api:version: !include ../schema/json/version.json
    api:error: !include ../schema/json/error.json

/{version}:
    uriParameters:
        version:
            enum: ["v1"]
            type: "string"
    get:
        responses:
            200:
                body:
                    type: api:version
            404:
                body:
                    type: api:error